### ISSUE TITLE
Menu Bar misaligned

### ISSUE THREAD

**Issue by dsaharia** [python-gsoc/python-gsoc.github.io#51] opened 2018-12-30 19:24 UTC
The right menu bar is slightly misaligned and covers the Gsoc lettering, which looks bad.

**Comment by terriko** [comment] 2019-01-02 01:30
There shouldn't be a right menu bar, only a left one.  Can you provide a screenshot and more information about what browser you're using?

**Comment by dsaharia** [comment] 2019-01-02 05:11
I'm sorry I meant a left one.
Os- MacOS
Browser - Chrome
![screenshot 2019-01-02 at 10 40 32 am](https://user-images.githubusercontent.com/29610517/50580955-f45c4f00-0e7a-11e9-80f5-52ff8a5935c2.png)

**Comment by terriko** [comment] 2019-04-03 18:08
I haven't been able to duplicate this on my mac, but mine's fairly old so that's not necessarily surprising.  I'm guessing it's a real bug, but without a way to duplicate it I can't do much to fix it.  Patches welcome!

If I had to guess, it's probably a minor bug in the purecss.io code we use for the menu at a very specific width, so that might be a good place to start for anyone who wants to debug it.

**Comment by akmadian** [comment] 2019-04-05 06:11
I was not able to replicate this either :/

Windows 10 Pro 1803; 17134.648 (64 bit)
Chrome 73.0.3683.86 (64 bit)

**Comment by dsaharia** [comment] 2019-04-05 11:14
I am able to replicate the misalignment.
MacOS
Chrome
`http://python-gsoc.org/`

**Comment by botanicvelious** [comment] 2019-04-05 20:03
@dsaharia what version of osx and chrome?

**Comment by dsaharia** [comment] 2019-04-07 17:34
MacOS Mojave 10.14.3
Chrome 73.0.3683.86

**Comment by OO7kartik** [comment] 2019-12-21 07:22
No luck in replicating this :(

Ubuntu 19.10
Chrom 79.0.3945.88  (64-bit)

**Comment by lucasdutraf** [comment] 2020-01-16 03:58
I've also tried to replicate this and got nothing.

Ubuntu 18.04
Chrome 78.0.3904.108 (64-bits)
Firefox Browser 72.0.1 (64-bits)

**Comment by warthog9** [comment] 2020-01-29 07:09
No luck replicating this on:
- macOS Mojave / Chrome 79.0.3945.130
- macOS Mojave / Firefox 65.0
- Windows 10 / Chrome 79.0.3945.130
- Windows 10 / Firefox 71 & 72.0.2
- Windows 10 / Edge (some version I don't care to figure out which)
- Fedora 30 / Firefox 72.0.1

Did replicate, weirdly, on
- Fedora 30 / Chrome 79.0.3945.130

AHHHHHH there we go, because I'm getting "old", and my T490 Fedora 30 system has a delightfully high dpi screen, I set the Font Size to "Large" (Chrome defaults to "Medium (recommended)"), which seems to do the "wrong" thing. (confirmed changing this setting in windows does make it wrong).

**Comment by arghyakamal1** [comment] 2020-02-21 07:10
Have you tried Mozilla Firefox? I think it can help you

**Comment by v-parmar** [comment] 2022-12-11 12:07
This issue was already closed, so why was it opened again ?

**Comment by jprankawat** [comment] 2023-01-20 14:36
I would like to work on this issue  if it is not closed.

**Comment by Rajeshwari0826** [comment] 2023-02-01 04:52
I want to work on this issue, please let me work on it.

**Comment by terriko** [comment] 2023-02-15 20:13
I have no idea why this was re-opened.  I'm going to re-close it.

**Closed by terriko** 2023-02-15 20:13 UTC
Labels: help wanted
